### ISSUE TITLE
Go extension is slow and sometimes "eats" characters when typing quickly

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-go-extension#10]
When Network is not very fast Theia becomes unusable and keyboard is no  accepting input or the input is showing after delay.

Maybe related: at times, it seems like the editor rolls-back some typed characters. We do not know for sure, but one hypothesis is that adverse network conditions causes some editor updates to be lost, after being echo'ed in the editor. e.g. you type "example" and see it in the editor, then the last few characters disappear and we are left with "examp".

**Comment by hexa00** [comment]
Is that related to go only ?

Guess we have to test more..

**Comment by akosyakov** [comment]
Eating characters should have been fixed by https://github.com/theia-ide/theia/commit/4a9d238eb67a2f5f7c6124128ef1373aae18e47b.

**Comment by marcdumais-work** [comment]
thanks for the info @akosyakov - we will observe if this happens still and update or close this issue.

**Comment by marcdumais-work** [comment]
For the "eating characters" part, duplicate of https://github.com/theia-ide/theia/issues/1185 . Will investigate the "slowness" aspect separately and open new issue if needed.
