### ISSUE TITLE
Add language config and textmate grammar

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-go-extension#13]
Theia no longer comes with basic go support, si this extension should register the language and add the grammar and configuration.

see
 - https://github.com/Microsoft/monaco-languages/tree/master/src/go (language config)
 - https://github.com/Microsoft/vscode/tree/master/extensions/go/syntaxes (textmate grammar)
 - https://github.com/theia-ide/theia/pull/2253/commits/1b81563144d802580ade4863b8130119aac77d29 (example)

**Comment by svenefftinge** [comment]
@JanKoehnlein would you have time to look into it?

**Comment by JanKoehnlein** [comment]
I'll try to

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/theia-go-extension/pull/14

**Comment by JanKoehnlein** [comment]
Done
